name: Interface Exporter Action - Production

on:
  push:
    branches:
      - main

jobs:
  generate-and-publish-interfaces:
    name: Generate Interfaces
    runs-on: ubuntu-latest
    strategy:
      matrix:
        publish_type: ["abi"]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build project and generate out directory
        run: yarn build

      - name: Export Interfaces - ${{ matrix.publish_type }}
<<<<<<< HEAD
        uses: defi-wonderland/interface-exporter-action@v1.2.0
        with:
          out_dir: "artifacts"
=======
        uses: defi-wonderland/interface-exporter-action@v1.x # TODO: Update when bug fix in the last version of interfaces exporter merged
        with:
          out_dir: ./artifacts/contracts
          interfaces_dir: "./contracts"
>>>>>>> 7a323b37d37dd3680953e654aa01d4a5f5af826a
          typing_type: "${{ matrix.publish_type }}"
          package_name: "prophet-batching-${{ matrix.publish_type }}"
          destination_dir: "exported-interfaces/prophet-batching-${{ matrix.publish_type }}"

      - name: Publish
        run: cd exported-interfaces/prophet-batching-${{ matrix.publish_type }} && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
